SKIP_ROWS = 7
INITIAL_OFFSET_INDEX = 3
ROW_MAPPER_CUTOFF_INDEX = 4  # NON-inclusive
TIME_DIFF_INDEX = 3
ROB_OR_LAP_INDEX = 1
COLUMNS_USED = [0, 2, 3, 4, 5, 6, 7]

MUS1 = "MUS1"
MUS2 = "MUS2"
MUS3 = "MUS3"
MUS4 = "MUS4"
MUS5 = "MUS5"
MUS6 = "MUS6"

TIME = "TIME"

ROB = "ROB"
LAP = "LAP"

# maps muscles to columns
MUS2COL = {MUS1:2, MUS2:3, MUS3:4, MUS4:5, MUS5:6, MUS6:7}
# maps time to column
T2COL = {TIME: 0}

DIVIDE_MARKER = "Interval="